[project]
name = 'HireVibesDAO'
description = ''
authors = []
telemetry = false
cache_dir = '.\.cache'

[[project.requirements]]
contract_id = 'SP27BB1Y2DGSXZHS7G9YHKTSH6KQ6BD3QG0AN3CR9.vibes-token'

[[project.requirements]]
contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'
[contracts.extension-trait]
path = 'contracts/extension-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.proposal-trait]
path = 'contracts/proposal-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.vde000-treasury]
path = 'contracts/vde000-treasury.clar'
clarity_version = 1
epoch = 2.0

[contracts.vde001-proposal-voting]
path = 'contracts/vde001-proposal-voting.clar'
clarity_version = 1
epoch = 2.0

[contracts.vde002-proposal-submission]
path = 'contracts/vde002-proposal-submission.clar'
clarity_version = 1
epoch = 2.0

[contracts.vde003-emergency-proposals]
path = 'contracts/vde003-emergency-proposals.clar'
clarity_version = 1
epoch = 2.0

[contracts.vde004-emergency-execute]
path = 'contracts/vde004-emergency-execute.clar'
clarity_version = 1
epoch = 2.0

[contracts.vdp000-bootstrap]
path = 'contracts/vdp000-bootstrap.clar'
clarity_version = 2
epoch = 2.1

[contracts.vibeDAO]
path = 'contracts/vibeDAO.clar'
clarity_version = 1
epoch = 2.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
