[project]
name = 'HireVibesDAO'
description = ''
authors = []
telemetry = false
cache_dir = '.\.cache'

[[project.requirements]]
contract_id = 'SP27BB1Y2DGSXZHS7G9YHKTSH6KQ6BD3QG0AN3CR9.vibes-token'
[contracts.extension-trait]
path = 'contracts/extension-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.proposal-trait]
path = 'contracts/proposal-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.vde000-treasury]
path = 'contracts/vde000-treasury.clar'
clarity_version = 1
epoch = 2.0

[contracts.vde001-proposal-voting]
path = 'contracts/vde001-proposal-voting.clar'
clarity_version = 1
epoch = 2.0

[contracts.vibeDAO]
path = 'contracts/vibeDAO.clar'
clarity_version = 1
epoch = 2.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
